version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NETPULSE
    command: gunicorn backend.backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=backend.backend.settings
      - PYTHONPATH=/app

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A backend.backend worker --loglevel=info
    depends_on:
      - backend
      - redis
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=backend.backend.settings
      - PYTHONPATH=/app

