version: "3.9"

services:
  web:
    build:
      context: .
    container_name: backend_web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_broker
    ports:
      - "6379:6379"
